spring:
  application:
    name: jakarta

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        batch_size: 30
        fetch_size: 30
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      cache:
        use_query_cache: true
        use_second_level_cache: true

server:
  port: ${APP_PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
